language: node_js
node_js:
- 0.8
- '0.10'
before_script:
- npm install -g grunt-cli
env:
  global:
  - secure: Jz33rvC+z7oeMnmY2EPVP2jwovY1xBd539Golz6Isg5zHW6t9Ez1uSG3WlMsqJlq+ovgBoXlhRVYnkS4gBTuDnY/n3DgISaDyHuc9z3xAiXyefF6m2aMGZQyNJPvdDGH+edItmh/e5tnmM5OAmu4vm/uAxYCvk9ElfKFI/4KknM=
  - secure: Fs6t+cvD3P7omVtQPEr+G1HCPX+2xrOHKTdIjUJbxI3+VcM1Q27OqA5qKz8GL2+u73LyeodI/X9O7Q18ZXnKHy9QM59Gp01W+/tax3Vknw9KW46/HlTxidlWaQkKFoV4SpgqM4vQGp6YUWN6oe/5aaNPG9C+sr1FIBHYICo3/V4=
